notify-update: true
worlds:
  - spawn
  - test
ores:
  COAL_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_COAL_ORE:
    enable: true
    replace-default-in: 30
  IRON_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_IRON_ORE:
    enable: true
    replace-default-in: 30
  COPPER_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_COPPER_ORE:
    enable: true
    replace-default-in: 30
  GOLD_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_GOLD_ORE:
    enable: true
    replace-default-in: 30
  REDSTONE_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_REDSTONE_ORE:
    enable: true
    replace-default-in: 30
  EMERALD_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_EMERALD_ORE:
    enable: true
    replace-default-in: 30
  LAPIS_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_LAPIS_ORE:
    enable: true
    replace-default-in: 30
  DIAMOND_ORE:
    enable: true
    replace-default-in: 30
  DEEPSLATE_DIAMOND_ORE:
    enable: true
    replace-default-in: 30
  NETHER_GOLD_ORE:
    enable: true
    replace-default-in: 30
  NETHER_QUARTZ_ORE:
    enable: true
    replace-default-in: 30
