notify-update: true
worlds:
  - spawn
  - test
ores:
  COAL_ORE:
    enable: true
    item-giving:
      type: COAL
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_COAL_ORE:
    enable: true
    item-giving:
      type: COAL
      min: 1
      max: 1
    replace-default-in: 30
  IRON_ORE:
    enable: true
    item-giving:
      type: RAW_IRON
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_IRON_ORE:
    enable: true
    item-giving:
      type: RAW_IRON
      min: 1
      max: 1
    replace-default-in: 30
  COPPER_ORE:
    enable: true
    item-giving:
      type: RAW_COPPER
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_COPPER_ORE:
    enable: true
    item-giving:
      type: RAW_COPPER
      min: 1
      max: 1
    replace-default-in: 30
  GOLD_ORE:
    enable: true
    item-giving:
      type: RAW_GOLD
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_GOLD_ORE:
    enable: true
    item-giving:
      type: RAW_GOLD
      min: 1
      max: 1
    replace-default-in: 30
  REDSTONE_ORE:
    enable: true
    item-giving:
      type: REDSTONE
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_REDSTONE_ORE:
    enable: true
    item-giving:
      type: REDSTONE
      min: 1
      max: 1
    replace-default-in: 30
  EMERALD_ORE:
    enable: true
    item-giving:
      type: EMERALD
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_EMERALD_ORE:
    enable: true
    item-giving:
      type: EMERALD
      min: 1
      max: 1
    replace-default-in: 30
  LAPIS_ORE:
    enable: true
    item-giving:
      type: LAPIS_LAZULI
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_LAPIS_ORE:
    enable: true
    item-giving:
      type: LAPIS_LAZULI
      min: 1
      max: 1
    replace-default-in: 30
  DIAMOND_ORE:
    enable: true
    item-giving:
      type: DIAMOND
      min: 1
      max: 1
    replace-default-in: 30
  DEEPSLATE_DIAMOND_ORE:
    enable: true
    item-giving:
      type: DIAMOND
      min: 1
      max: 1
    replace-default-in: 30
  NETHER_GOLD_ORE:
    enable: true
    item-giving:
      type: RAW_GOLD
      min: 1
      max: 1
    replace-default-in: 30
  NETHER_QUARTZ_ORE:
    enable: true
    item-giving:
      type: QUARTZ
      min: 1
      max: 1
    replace-default-in: 30
